---
# tasks file for test-var-pass-debug

- name: task 1
  debug:
          msg: "var1={{ var1 }}"

- name: task 2
  debug:
          msg: "var2={{ var2 }}"

- name: task 3
  debug:
          msg: "var3={{ var3 }}"

- name: task 4
  debug:
          msg: "var4={{ var4 }}"
- name: task 5
  debug:
          msg: "var5={{ var5 }}"

- name: task 6 - render template
  debug:
          msg: "{{ lookup('template', 'app.conf.j2') }}"
